# Generated by Django 5.1.5 on 2025-02-04 16:36

import django.db.models.deletion
import podrings.creative.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apple_id', models.PositiveIntegerField(unique=True, verbose_name='Apple Podcasts ID')),
                ('op3_id', models.UUIDField(blank=True, editable=False, null=True, verbose_name='OP3 ID')),
                ('name', models.CharField(max_length=1024)),
                ('rss', models.URLField(max_length=1024, verbose_name='RSS')),
                ('website', models.URLField(max_length=255)),
                ('artwork', models.ImageField(max_length=255, upload_to=podrings.creative.models.Podcast.upload_artwork)),
                ('description', models.TextField(blank=True, null=True)),
                ('downloads_per_month', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('fetched_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('owner_email', models.EmailField(max_length=255)),
                ('invited_on', models.DateTimeField(blank=True, null=True)),
                ('claimed_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'get_latest_by': 'created_on',
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('audio', models.FileField(max_length=255, upload_to=podrings.creative.models.Promo.upload_audio)),
                ('duration', models.PositiveIntegerField(null=True)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promos', to='creative.podcast')),
            ],
            options={
                'ordering': ('-created_on',),
                'get_latest_by': 'created_on',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(db_index=True, max_length=1024)),
                ('title', models.CharField(max_length=1024)),
                ('published_on', models.DateTimeField()),
                ('enclosure', models.URLField(max_length=1024)),
                ('duration', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('webpage', models.URLField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('full', 'Full'), ('bonus', 'Bonus'), ('trailer', 'Trailer')], max_length=10, null=True)),
                ('season', models.PositiveIntegerField(blank=True, null=True)),
                ('episode', models.PositiveIntegerField(blank=True, null=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='creative.podcast')),
            ],
            options={
                'ordering': ('-season', '-episode', '-published_on'),
                'get_latest_by': 'published_on',
                'unique_together': {('identifier', 'podcast')},
            },
        ),
    ]
